# Generated by Django 4.1 on 2023-07-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("last", models.IntegerField()),
                ("applicant", models.IntegerField()),
                ("job_site", models.CharField(max_length=255)),
                ("job_type", models.CharField(max_length=255)),
                ("req", models.CharField(max_length=255)),
                ("des", models.TextField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254)),
            ],
        ),
    ]
